### ISSUE TITLE
Missing bower.json file

### ISSUE THREAD

**Issue by fresheneesz** [MichaelRoberts214/beholder#1]
When running `bower install` I get `ENOENT No bower.json present`

**Comment by fresheneesz** [comment]
nor does it have a package.json file. I installed all 5 dependencies manually using npm, so not sure why you're using both bower and npm

**Comment by MichaelRoberts214** [comment]
Thank you for bringing this to my attention @fresheneesz 

The issue was that I had put package.json and bower.json in my .gitignore. I modified the .gitignore and README.md and pushed the files into the repository. Future work includes removing elements of the original project Beholder was built from to reduce the dependency count.
